### ISSUE TITLE
Can't successfully import MiniCalendar

### ISSUE THREAD

**Issue by kcfgl** [doublenot/react-native-datepicker#7]
This component looks absolutely perfect for my app!  Nice work. 

But I can't seem to get the import statement correct so that the app won't error out. I've tried a standard: `var MiniCalendar = require('react-native-minicalendar');` OR `import {MiniCalendar} from ('react-native-minicalendar');`

Both error out in RN@0.32

Is there a new way to import in latest RN?  Thanks!

**Comment by kcfgl** [comment]
Looks like its just not compatible with the latest RN versions. Any plans to update?  Hoping so as its a cool looking component.

**Comment by license2e** [comment]
@kcfgl Can you post the error? I will check it out later tonight...

**Comment by license2e** [comment]
@kcfgl Please try the latest version published, should work now...

**Comment by kcfgl** [comment]
Great, thanks! I'll give it a try.  Really nice mini calendar. 

Kane
